// <auto-generated />

using System.Collections.Generic;

namespace StronglyTyped.FeatureFlags.Consumer;

partial interface IFeatureFlagsAccessor
{

}

partial class FeatureFlags
{
// Items => SaluteUniverse,OtherFeature 
}
